version: 2

sources:
    - name: staging
      database: axial-copilot-376216
      schema: trips_data_all
    
      tables:
        - name: green_tripdata_2019_2020
        - name: yellow_tripdata_2019_2020